<a href="https://colab.research.google.com/github/vincentvega1/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

In [ ]:
dir(np)

In [ ]:
help(np.array)

In [7]:
x=np.array([1,3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [14]:
x=np.arange(start=1 , stop=100, step=5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [24]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
a.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
A=np.array([[3,1],[4,2]])
B=np.array([[3,-1],[3,2]])
print(A)
print(B)

[[3 1]
 [4 2]]
[[ 3 -1]
 [ 3  2]]


In [34]:
np.dot(A,B)

array([[12, -1],
       [18,  0]])

In [35]:
np.dot(B,A)

array([[ 5,  1],
       [17,  7]])

In [36]:
np.random.seed(0)

In [37]:
np.random.randn()

1.764052345967664

In [38]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [39]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [40]:
np.random.rand(10,2)

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

In [43]:
np.random.randint(10)

1

In [44]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.random.shuffle(data)
data

array([7, 6, 8, 5, 2, 9, 0, 4, 3, 1])

In [61]:
A=np.random.rand(5)
A

array([0.61801543, 0.4287687 , 0.13547406, 0.29828233, 0.56996491])

In [54]:
np.argmax(A)

2

In [55]:
A[np.argmax(A)]

0.9560836347232239

In [56]:
np.argmin(A)

4

In [62]:
np.argsort(A)

array([2, 3, 1, 4, 0])

In [63]:
np.mean(A)

0.41010108616487073

In [65]:
(np.sum(A))/5

0.41010108616487073

In [67]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
A[2:5]

array([2, 3, 4])

In [74]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
A[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [82]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])