<a href="https://colab.research.google.com/github/vincentvega1/data-science-bootcamp/blob/main/supervised/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

In [39]:
data={
    'size':['XL', 'L', 'M','L','M'],
    'color':['red','green','blue','green','reed'],
    'gender':['female', 'male', 'male', 'female', 'female'],
    'price':[199.0,89.0,99.0,129.0,79.0],
    'weight':[500,450,300,380,410],
    'bought':['yes','no','yes','no','yes']

}
print(data)
df_raw=pd.DataFrame(data=data)
df_raw

{'size': ['XL', 'L', 'M', 'L', 'M'], 'color': ['red', 'green', 'blue', 'green', 'reed'], 'gender': ['female', 'male', 'male', 'female', 'female'], 'price': [199.0, 89.0, 99.0, 129.0, 79.0], 'weight': [500, 450, 300, 380, 410], 'bought': ['yes', 'no', 'yes', 'no', 'yes']}


size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M   reed  female   79.0     410    yes

In [40]:
df=df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [41]:
for col in ['size', 'color', 'gender','bought']:
  df[col]=df[col].astype('category')

df['weight']=df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 812.0 bytes


In [42]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [43]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      4   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [44]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [45]:
le.classes_

array(['no', 'yes'], dtype=object)

In [46]:
df['bought']=le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M   reed  female   79.0   410.0       1

In [47]:
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [48]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [49]:
encoder=OneHotEncoder(drop='first',sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [50]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M   reed  female   79.0   410.0       1

In [51]:
pd.get_dummies(data=df)

price  weight  bought  size_L  size_M  size_XL  color_blue  color_green  \
0  199.0   500.0       1       0       0        1           0            0   
1   89.0   450.0       0       1       0        0           0            1   
2   99.0   300.0       1       0       1        0           1            0   
3  129.0   380.0       0       1       0        0           0            1   
4   79.0   410.0       1       0       1        0           0            0   

   color_red  color_reed  gender_female  gender_male  
0          1           0              1            0  
1          0           0              0            1  
2          0           0              0            1  
3          0           0              1            0  
4          0           1              1            0

In [52]:
pd.get_dummies(data=df, drop_first=True)

price  weight  bought  size_M  size_XL  color_green  color_red  color_reed  \
0  199.0   500.0       1       0        1            0          1           0   
1   89.0   450.0       0       0        0            1          0           0   
2   99.0   300.0       1       1        0            0          0           0   
3  129.0   380.0       0       0        0            1          0           0   
4   79.0   410.0       1       1        0            0          0           1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0

In [53]:
pd.get_dummies(data=df, drop_first=True,prefix='new')

price  weight  bought  new_M  new_XL  new_green  new_red  new_reed  \
0  199.0   500.0       1      0       1          0        1         0   
1   89.0   450.0       0      0       0          1        0         0   
2   99.0   300.0       1      1       0          0        0         0   
3  129.0   380.0       0      0       0          1        0         0   
4   79.0   410.0       1      1       0          0        0         1   

   new_male  
0         0  
1         1  
2         1  
3         0  
4         0

In [54]:
print(f"{df['price']}\n")
print(f"Średnia:{df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")


0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia:119.0
Odchylenie standardowe: 48.4768


In [55]:
(df['price']-df['price'].mean())/df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [56]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
df[['price', 'weight']]=scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M   reed  female -0.922531  0.029696       1

PRzygotowanie do modelu

In [57]:
df=df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M   reed  female   79.0     410    yes

In [60]:
le=LabelEncoder()

df['bought']=le.fit_transform(df['bought'])
scaler=StandardScaler()
df[['price','weight']]=scaler.fit_transform(df[['price','weight']])

df=pd.get_dummies(data=df,drop_first=True)

df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          0   

   color_reed  gender_male  
0           0            0  
1           0            1  
2           0            1  
3           0            0  
4           1            0